### ISSUE TITLE
A compiled version ?

### ISSUE THREAD

**Issue by Djyp** [soulshake/gandi-droid#1]
Hi, I am not an android developper and I have a great deal to learn and set up to make your project as an apk... Could you please add an apk to your repository so I can try your app ? And maybe I'd use it every day instead of using the non-mobile website...

Thanks, whatever your answer is :)

**Comment by soulshake** [comment]
Alas, I'm not an Android developer either. Maybe @ColdSauce can help?

**Comment by sylvia43** [comment]
If he's busy I can get to it in an hour or two. Currently in class...

**Comment by soulshake** [comment]
Let us know what you come up with, @anubiann00b :)

**Comment by sylvia43** [comment]
Should I give you a copy signed with my key? Can I build an unsigned copy?

**Comment by sylvia43** [comment]
Wait there's no content here, just an empty class stub... Is the code not pushed?

```
public class StartActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_start);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.start, menu);
        return true;
    }
}
```

**Comment by soulshake** [comment]
I haven't looked at it and I don't know Android at all, so I have no idea what has been done so far. It's possible @ColdSauce hasn't pushed much, if anything. In that case, it would be rad if either of you got something started (even if it's a bare minimum)!

**Comment by sylvia43** [comment]
Do you guys have a plan? Mockups? API's?

**Comment by ColdSauce** [comment]
Hey guys! Sorry, I have been very busy this past week so I couldn't really respond to this issue.

I have only created the project. I was going to work on it but I had a lot of things to do and never really continued with it.

**Comment by ColdSauce** [comment]
@anubiann00b You wanna hop on Google Hangouts this weekend and plan this out? I just got a lot of free time now.

**Comment by sylvia43** [comment]
This weekend is CodeDay, next week school's off though, maybe then?

**Comment by ColdSauce** [comment]
:+1: Sounds good!
